# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(email: 'a@a', name: 'Excalibur', password: 'aaa')
User.create(email: 'a@b', name: 'Mag', password: 'aab')
User.create(email: 'a@c', name: 'Volt', password: 'aac')
User.create(email: 'a@d', name: 'Chroma', password: 'aad')
User.create(email: 'a@e', name: 'Gara', password: 'aae')
User.create(email: 'a@f', name: 'Trinity', password: 'aaf')
User.create(email: 'a@g', name: 'Rhino', password: 'aag')
User.create(email: 'a@h', name: 'Mirage', password: 'aah')
User.create(email: 'a@i', name: 'Limbo', password: 'aai')
User.create(email: 'a@j', name: 'Wukong', password: 'aaj')
User.create(email: 'a@k', name: 'Ember', password: 'aak')
User.create(email: 'a@l', name: 'Atlas', password: 'aal')
User.create(email: 'a@m', name: 'Inaros', password: 'aam')
User.create(email: 'a@n', name: 'Banshee', password: 'aan')
Group.create(name: 'Mugiwara', admin_id: '1')
Group.create(name: 'Whitebeard', admin_id: '3')
Group.create(name: 'Blackbeard', admin_id: '5')
Group.create(name: 'Killer Whale', admin_id: '7')
Membership.create(user_id: '1', group_id: '1')
Membership.create(user_id: '1', group_id: '3')
Membership.create(user_id: '1', group_id: '4')
Membership.create(user_id: '2', group_id: '1')
Membership.create(user_id: '2', group_id: '2')
Membership.create(user_id: '3', group_id: '2')
Membership.create(user_id: '3', group_id: '3')
Membership.create(user_id: '3', group_id: '4')
Membership.create(user_id: '4', group_id: '1')
Membership.create(user_id: '4', group_id: '2')
Membership.create(user_id: '5', group_id: '3')
Membership.create(user_id: '6', group_id: '4')
Membership.create(user_id: '6', group_id: '3')
Membership.create(user_id: '7', group_id: '1')
Membership.create(user_id: '7', group_id: '3')
Membership.create(user_id: '7', group_id: '4')
Membership.create(user_id: '8', group_id: '1')
Membership.create(user_id: '8', group_id: '2')
Membership.create(user_id: '8', group_id: '4')
Membership.create(user_id: '9', group_id: '2')
Membership.create(user_id: '9', group_id: '3')
Membership.create(user_id: '10', group_id: '4')
Membership.create(user_id: '11', group_id: '3')
Membership.create(user_id: '11', group_id: '4')
Membership.create(user_id: '12', group_id: '2')
Membership.create(user_id: '12', group_id: '3')
Membership.create(user_id: '12', group_id: '4')
Membership.create(user_id: '13', group_id: '1')
Membership.create(user_id: '14', group_id: '1')
Membership.create(user_id: '14', group_id: '3')
Membership.create(user_id: '14', group_id: '4')
